// A removal plan for unused functions, grouped by file. "Safe" means nothing
// calls the function and its name appears nowhere else in the repository;
// "check" means the name shows up elsewhere (a string, template, config or
// reflection call) so it may be invoked dynamically.

export interface CleanupItem { name: string; line: number; lines: number; confidence: 'safe' | 'check'; mentions: string[] }
export interface CleanupFile { path: string; items: CleanupItem[]; lines: number; wholeFile: boolean }
export interface CleanupPlan { files: CleanupFile[]; totals: { functions: number; lines: number; safe: number; check: number; wholeFiles: number } }

const ENTRY_NAME = /(^|\/)(main|index|app|server|cli|manage|wsgi|asgi|__main__|__init__|setup|conftest)\.[a-z0-9]+$/i;

function endpoint(value: any): string {
  return typeof value === 'object' && value ? value.id : value;
}

export function buildCleanupPlan(data: any): CleanupPlan {
  const dead: any[] = data?.deadFunctions ?? [];
  const functionsIn = new Map<string, number>((data?.files ?? []).map((f: any) => [f.path, (f.functions ?? []).length]));
  const depended = new Set<string>();
  (data?.connections ?? []).forEach((c: any) => { if (!c.kind && endpoint(c.source) !== endpoint(c.target)) depended.add(endpoint(c.source)); });

  const byFile = new Map<string, CleanupItem[]>();
  dead.forEach(fn => {
    if (!fn.file) return;
    const mentions: string[] = fn.mentions ?? [];
    const item: CleanupItem = { name: fn.name, line: fn.line ?? 0, lines: fn.codeLines ?? 0, confidence: mentions.length ? 'check' : 'safe', mentions };
    if (!byFile.has(fn.file)) byFile.set(fn.file, []);
    byFile.get(fn.file)!.push(item);
  });

  const files: CleanupFile[] = [...byFile].map(([path, items]) => {
    items.sort((a, b) => a.line - b.line);
    // Everything in the file is unused, nothing imports from it, it isn't an
    // entry point, and no unused name is referenced elsewhere.
    const wholeFile = items.length === (functionsIn.get(path) ?? -1) && !depended.has(path) && !ENTRY_NAME.test(path) && items.every(i => i.confidence === 'safe');
    return { path, items, lines: items.reduce((n, i) => n + i.lines, 0), wholeFile };
  }).sort((a, b) => Number(b.wholeFile) - Number(a.wholeFile) || b.lines - a.lines || a.path.localeCompare(b.path));

  const all = files.flatMap(f => f.items);
  return {
    files,
    totals: {
      functions: all.length,
      lines: all.reduce((n, i) => n + i.lines, 0),
      safe: all.filter(i => i.confidence === 'safe').length,
      check: all.filter(i => i.confidence === 'check').length,
      wholeFiles: files.filter(f => f.wholeFile).length,
    },
  };
}

export function planToMarkdown(plan: CleanupPlan, repoName: string): string {
  const code = (s: string) => '`' + s.replace(/`/g, "'") + '`';
  const lines = [`## Dead code cleanup: ${repoName}`, '', `${plan.totals.functions} unused functions, about ${plan.totals.lines} lines. Generated by Structrace.`, ''];
  const whole = plan.files.filter(f => f.wholeFile);
  if (whole.length) {
    lines.push('### Delete whole files', '');
    whole.forEach(f => lines.push(`- [ ] ${code(f.path)} (${f.items.length} functions, ${f.lines} lines)`));
    lines.push('');
  }
  const safe = plan.files.filter(f => !f.wholeFile).flatMap(f => f.items.filter(i => i.confidence === 'safe').map(i => ({ f, i })));
  if (safe.length) {
    lines.push('### Remove functions', '');
    safe.forEach(({ f, i }) => lines.push(`- [ ] ${code(f.path)}: ${code(`${i.name}()`)} line ${i.line} (${i.lines} lines)`));
    lines.push('');
  }
  const check = plan.files.flatMap(f => f.items.filter(i => i.confidence === 'check').map(i => ({ f, i })));
  if (check.length) {
    lines.push('### Check before removing — the name appears elsewhere', '');
    check.forEach(({ f, i }) => lines.push(`- [ ] ${code(f.path)}: ${code(`${i.name}()`)} — mentioned in ${i.mentions.map(code).join(', ')}`));
    lines.push('');
  }
  return lines.join('\n');
}
