// CODEOWNERS from commit history, and an audit of an existing CODEOWNERS file.
// Pure logic; the GitHub calls live in the component that uses it.

export interface OwnerRule { line: number; pattern: string; owners: string[] }
export interface AreaActivity { area: string; files: number; authors: Array<{ login: string; commits: number }>; commits: number }
export interface Suggestion { area: string; owners: string[]; share: number; commits: number }
export type Finding =
  | { kind: 'stale-owner'; line: number; pattern: string; owner: string; area: string }
  | { kind: 'no-match'; line: number; pattern: string }
  | { kind: 'unowned'; area: string; files: number; suggested: string[] };

export const LOCATIONS = ['.github/CODEOWNERS', 'CODEOWNERS', 'docs/CODEOWNERS'];
const MAX_AREAS = 15;
const SPLIT_SHARE = 0.25;

export function parseCodeowners(text: string): OwnerRule[] {
  const rules: OwnerRule[] = [];
  text.split(/\r?\n/).forEach((raw, i) => {
    const line = raw.replace(/(^|\s)#.*$/, '').trim();
    if (!line) return;
    const [pattern, ...owners] = line.split(/\s+/);
    rules.push({ line: i + 1, pattern, owners });
  });
  return rules;
}

// CODEOWNERS pattern semantics (gitignore-like): a leading "/" anchors to the
// root, a trailing "/" means everything inside, a pattern without a slash
// matches at any depth, "*" stays within a folder, "**" spans folders.
export function patternMatcher(pattern: string): RegExp {
  let p = pattern;
  const anchored = p.startsWith('/') || p.slice(0, -1).includes('/');
  p = p.replace(/^\//, '');
  const dirOnly = p.endsWith('/');
  if (dirOnly) p = p.slice(0, -1);
  let re = '';
  for (let i = 0; i < p.length; i++) {
    const c = p[i];
    if (c === '*' && p[i + 1] === '*') { re += '.*'; i++; if (p[i + 1] === '/') i++; }
    else if (c === '*') re += '[^/]*';
    else if (c === '?') re += '[^/]';
    else re += c.replace(/[.+^${}()|[\]\\]/g, '\\$&');
  }
  const prefix = anchored ? '^' : '^(?:.*/)?';
  // A name matches the file itself or, as a folder, everything under it.
  return new RegExp(`${prefix}${re}${dirOnly ? '/.*' : '(?:/.*)?'}$`);
}

// GitHub applies the LAST matching rule.
export function ownersOf(path: string, rules: OwnerRule[]): OwnerRule | null {
  for (let i = rules.length - 1; i >= 0; i--) if (patternMatcher(rules[i].pattern).test(path)) return rules[i];
  return null;
}

// Ownership areas: top-level folders, with any folder holding more than a
// quarter of the files split one level deeper. Files at the repository root
// are left out — they are usually shared configuration.
export function suggestAreas(paths: string[]): Array<{ area: string; files: number }> {
  const count = (depth: number, within?: string) => {
    const m = new Map<string, number>();
    paths.forEach(p => {
      if (within && !p.startsWith(`${within}/`)) return;
      const parts = p.split('/');
      if (parts.length <= depth) return;
      const key = parts.slice(0, depth).join('/');
      m.set(key, (m.get(key) ?? 0) + 1);
    });
    return m;
  };
  const areas: Array<{ area: string; files: number }> = [];
  for (const [top, n] of count(1)) {
    const children = count(2, top);
    if (n > paths.length * SPLIT_SHARE && children.size > 1) {
      for (const [child, cn] of children) areas.push({ area: child, files: cn });
      const direct = n - [...children.values()].reduce((a, b) => a + b, 0);
      if (direct > 0) areas.push({ area: top, files: direct });
    } else areas.push({ area: top, files: n });
  }
  return areas.sort((a, b) => b.files - a.files || a.area.localeCompare(b.area)).slice(0, MAX_AREAS);
}

// Owners: the most active recent committers until they cover half the area's
// commits — at most three, each with at least 15% of them.
export function suggestOwners(activity: AreaActivity[]): Suggestion[] {
  return activity
    .filter(a => a.commits > 0)
    .map(a => {
      const owners: string[] = [];
      let covered = 0;
      for (const author of [...a.authors].sort((x, y) => y.commits - x.commits)) {
        if (owners.length >= 3 || author.commits / a.commits < 0.15) break;
        owners.push(`@${author.login}`);
        covered += author.commits;
        if (covered / a.commits >= 0.5) break;
      }
      return { area: a.area, owners, share: Math.round((covered / a.commits) * 100), commits: a.commits };
    })
    .filter(s => s.owners.length > 0);
}

export function renderCodeowners(suggestions: Suggestion[], months: number): string {
  const lines = [
    `# Generated by Structrace from the last ${months} months of commit history.`,
    '# Review before committing: replace people with @org/team handles where a team owns an area.',
    '# Later rules take precedence over earlier ones.',
    '',
  ];
  // Alphabetical puts a folder before its subfolders, so the more specific rule comes later and wins.
  [...suggestions].sort((a, b) => a.area.localeCompare(b.area)).forEach(s => lines.push(`/${s.area}/ ${s.owners.join(' ')}`));
  return lines.join('\n') + '\n';
}

export function auditCodeowners(rules: OwnerRule[], paths: string[], activity: AreaActivity[], suggestions: Suggestion[]): Finding[] {
  const findings: Finding[] = [];
  for (const rule of rules) {
    const re = patternMatcher(rule.pattern);
    const matched = paths.filter(p => re.test(p));
    if (!matched.length) { findings.push({ kind: 'no-match', line: rule.line, pattern: rule.pattern }); continue; }
    // A person (not a team or email) who hasn't committed in any area this rule covers.
    const areas = activity.filter(a => matched.some(p => p === a.area || p.startsWith(`${a.area}/`)));
    if (!areas.length) continue;
    for (const owner of rule.owners) {
      if (!owner.startsWith('@') || owner.includes('/')) continue;
      const login = owner.slice(1).toLowerCase();
      if (!areas.some(a => a.authors.some(x => x.login.toLowerCase() === login))) {
        findings.push({ kind: 'stale-owner', line: rule.line, pattern: rule.pattern, owner, area: areas[0].area });
      }
    }
  }
  for (const a of activity) {
    const sample = paths.find(p => p === a.area || p.startsWith(`${a.area}/`));
    if (sample && !ownersOf(sample, rules)) {
      findings.push({ kind: 'unowned', area: a.area, files: a.files, suggested: suggestions.find(s => s.area === a.area)?.owners ?? [] });
    }
  }
  return findings;
}
